# cloudbuild/deploy.yaml
# Deploy a Docker context to Cloud Run via Artifact Registry.

options:
  substitutionOption: ALLOW_LOOSE

substitutions:
  _REGION: us-central1
  _LOCATION: us-central1
  _SERVICE_NAME: vibesdk-generated-app
  _CONTEXT_TAR: cloudrun-context.tar.gz
  _REPOSITORY: vibesdk-apps

steps:
  # 1) Fetch and unpack the Docker build context
  - name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args:
      - -cu
      - |
        echo "CONTEXT_TAR value: ${_CONTEXT_TAR}"
        if [[ "${_CONTEXT_TAR}" == gs://* ]]; then
          echo "Downloading from GCS: ${_CONTEXT_TAR}"
          gsutil cp "${_CONTEXT_TAR}" /workspace/context.tar.gz
        else
          echo "Copying local file: ${_CONTEXT_TAR}"
          cp "${_CONTEXT_TAR}" /workspace/context.tar.gz
        fi
        mkdir -p /workspace/context
        tar -xzf /workspace/context.tar.gz -C /workspace/context

  # 2) Build & push image (compute a timestamp tag at runtime)
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -ceu
      - |
        IMG_TAG="$$(date +%Y%m%d-%H%M%S)"
        echo "$$IMG_TAG" > /workspace/img_tag
        FULL_URI="${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$${IMG_TAG}"

        echo "Using image tag: $$IMG_TAG"
        echo "Full image URI: $$FULL_URI"

        docker build --file /workspace/context/Dockerfile \
                     --tag "$$FULL_URI" /workspace/context
        docker push "$$FULL_URI"

  # 3) Deploy to Cloud Run (read the tag we just wrote)
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -ceu
      - |
        IMG_TAG="$$(cat /workspace/img_tag)"
        FULL_URI="${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$${IMG_TAG}"

        gcloud run deploy "${_SERVICE_NAME}" \
          --region="${_REGION}" \
          --image="$$FULL_URI" \
          --platform=managed \
          --allow-unauthenticated \
          --port=8080

# Optional: lets Cloud Build record the image (without a specific tag)
images:
  - "${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}"
