/* eslint-disable */
/**
 * Custom Type Definitions for Cloudflare Workers
 * 
 * This file contains type declarations that are:
 * 1. Not generated by Wrangler's `wrangler types` command
 * 2. Required for the application to compile correctly
 * 3. Custom extensions to Cloudflare Workers APIs
 * 
 * DO NOT REGENERATE THIS FILE - It is manually maintained.
 * When wrangler types is regenerated, this file remains intact.
 */

// Declare the cloudflare:workers module
declare module 'cloudflare:workers' {
	export const env: Env;
}

// Declare DurableObjectStub type for Cloudflare Workers
// This is a stub returned by DurableObjectNamespace.get() or .id()
// The stub can call methods on the Durable Object instance
interface DurableObjectStub<T = any> {
	// Durable Object stub methods
	fetch: (request: Request) => Promise<Response>;
	id: DurableObjectID;
	name?: string;
	// Methods that can be called on the stub (will be forwarded to the DO instance)
	isInitialized?: () => Promise<boolean>;
	getFullState?: () => Promise<any>;
	setState?: (state: any) => Promise<void>;
	deployToSandbox?: () => Promise<any>;
	deployToAppEngine?: () => Promise<any>;
	getSummary?: () => Promise<any>;
	getPreviewUrlCache?: () => Promise<string>;
	pushToGitHub?: (options: any) => Promise<any>;
	// Sandbox-specific methods (when T is Sandbox)
	exec?: (command: string, options?: any) => Promise<any>;
	writeFile?: (path: string, content: string) => Promise<void>;
	readFile?: (path: string) => Promise<{ success: boolean; content?: string }>;
	// Additional methods that may be available on the stub
	[key: string]: any;
}

type DurableObjectID = string | { id: string; name: string };

// Durable Object Jurisdiction type
type DurableObjectJurisdiction = 'eu' | 'fedramp' | undefined;

// Cloudflare Workers ExecutionContext type
interface ExecutionContext {
	waitUntil(promise: Promise<any>): void;
	passThroughOnException(): void;
	// Additional props that may be required by some frameworks (e.g., Hono)
	props?: Record<string, any>;
}

// Cloudflare Workers ExportedHandler type
interface ExportedHandler<Env = any> {
	fetch?: (request: Request, env: Env, ctx: ExecutionContext) => Response | Promise<Response>;
	scheduled?: (event: ScheduledEvent, env: Env, ctx: ExecutionContext) => void | Promise<void>;
	queue?: (batch: MessageBatch, env: Env, ctx: ExecutionContext) => void | Promise<void>;
	tail?: (events: TailEvent[], env: Env, ctx: ExecutionContext) => void | Promise<void>;
}

// Cloudflare Workers caches global
declare const caches: {
	default: Cache;
	open(cacheName: string): Promise<Cache>;
};

// KVNamespacePutOptions type
interface KVNamespacePutOptions {
	expirationTtl?: number;
	expiration?: number;
	metadata?: any;
}

// KVNamespaceListResult type
interface KVNamespaceListResult<T = unknown> {
	keys: KVNamespaceListKey<T>[];
	list_complete: boolean;
	cursor?: string;
}

// KVNamespaceListKey type
interface KVNamespaceListKey<T = unknown> {
	name: string;
	expiration?: number;
	metadata?: T;
}

// Cloudflare Workers KVNamespace type (extended with list method return type)
interface KVNamespace {
	get(key: string): Promise<string | null>;
	get(key: string, type: 'text'): Promise<string | null>;
	get(key: string, type: 'json'): Promise<any>;
	get(key: string, type: 'arrayBuffer'): Promise<ArrayBuffer | null>;
	get(key: string, type: 'stream'): Promise<ReadableStream | null>;
	put(key: string, value: string | ArrayBuffer | ArrayBufferView | ReadableStream): Promise<void>;
	put(key: string, value: string | ArrayBuffer | ArrayBufferView | ReadableStream, options?: KVNamespacePutOptions): Promise<void>;
	delete(key: string): Promise<void>;
	list(options?: { prefix?: string; limit?: number; cursor?: string }): Promise<KVNamespaceListResult>;
}

// Cloudflare Workers RateLimit type
interface RateLimit {
	limit(options: { key: string; limit?: number; period?: number }): Promise<{ success: boolean; limit?: number; remaining?: number; reset?: number }>;
}

// Cloudflare Workers WebSocketPair type
// WebSocketPair is a constructor function, not just a type
declare const WebSocketPair: {
    new (): WebSocketPair;
};

interface WebSocketPair {
	0: WebSocket;
	1: WebSocket;
}

// Cloudflare Workers DurableObject base class
declare class DurableObject {
	protected ctx: DurableObjectState;
	protected env: Env;
	constructor(ctx: DurableObjectState, env: Env);
	fetch(request: Request): Promise<Response>;
}

// Cloudflare Workers DurableObjectState type
interface DurableObjectState {
	id: DurableObjectID;
	waitUntil(promise: Promise<any>): void;
	storage: DurableObjectStorage;
	getWebSockets(): WebSocket[];
}

// Cloudflare Workers DurableObjectStorage type
interface DurableObjectStorage {
	get<T = unknown>(key: string): Promise<T | undefined>;
	get<T = unknown>(keys: string[]): Promise<Map<string, T>>;
	put<T = unknown>(key: string, value: T): Promise<void>;
	put<T = unknown>(entries: Record<string, T>): Promise<void>;
	delete(key: string): Promise<boolean>;
	delete(keys: string[]): Promise<number>;
	list<T = unknown>(options?: { start?: string; end?: string; prefix?: string; reverse?: boolean; limit?: number }): Promise<Map<string, T>>;
	transaction<T>(closure: (txn: DurableObjectTransaction) => Promise<T>): Promise<T>;
	getAlarm(): Promise<number | null>;
	setAlarm(scheduledTime: number | Date): Promise<void>;
	deleteAlarm(): Promise<void>;
	sync(): Promise<void>;
}

// Cloudflare Workers DurableObjectTransaction type
interface DurableObjectTransaction {
	get<T = unknown>(key: string): Promise<T | undefined>;
	get<T = unknown>(keys: string[]): Promise<Map<string, T>>;
	put<T = unknown>(key: string, value: T): void;
	put<T = unknown>(entries: Record<string, T>): void;
	delete(key: string): void;
	delete(keys: string[]): void;
	rollback(): void;
}

// ResponseInit with webSocket support (Cloudflare Workers extension)
interface ResponseInit {
	status?: number;
	statusText?: string;
	headers?: HeadersInit;
	webSocket?: WebSocket;
}

// HeadersInit type (standard Web API)
type HeadersInit = Headers | string[][] | Record<string, string>;

// D1Database type (Cloudflare D1 Database)
interface D1Database {
	prepare(query: string): D1PreparedStatement;
	exec(query: string): Promise<D1ExecResult>;
	batch<T = unknown>(statements: D1PreparedStatement[]): Promise<D1Result<T>[]>;
	withSession(sessionType: 'first-primary' | 'first-unconstrained'): D1Database;
}

// D1PreparedStatement type
interface D1PreparedStatement {
	bind(...values: unknown[]): D1PreparedStatement;
	first<T = unknown>(colName?: string): Promise<T | null>;
	first<T = unknown>(): Promise<T | null>;
	run<T = unknown>(): Promise<D1Result<T>>;
	all<T = unknown>(): Promise<D1Result<T>>;
	raw<T = unknown>(): Promise<T[]>;
}

// D1Result type
interface D1Result<T = unknown> {
	success: boolean;
	meta: {
		changed_db: boolean;
		changes: number;
		duration: number;
		last_row_id: number;
		rows_read: number;
		rows_written: number;
		size_after: number;
	};
	results?: T[];
}

// D1ExecResult type
interface D1ExecResult {
	count: number;
	duration: number;
}

// AI Gateway Providers type (for Cloudflare Workers AI Gateway)
type AIGatewayProviders = 'cloudflare' | 'openai' | 'anthropic' | 'google' | 'cohere' | 'huggingface' | 'replicate' | 'custom';

