/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: a434f433ba4653af25e418e89f62a09b)

// Declare the cloudflare:workers module
declare module 'cloudflare:workers' {
	export const env: Env;
}

// Declare DurableObjectStub type for Cloudflare Workers
// This is a stub returned by DurableObjectNamespace.get() or .id()
// The stub can call methods on the Durable Object instance
interface DurableObjectStub<T = any> {
	// Durable Object stub methods
	fetch: (request: Request) => Promise<Response>;
	id: DurableObjectID;
	name?: string;
	// Methods that can be called on the stub (will be forwarded to the DO instance)
	isInitialized?: () => Promise<boolean>;
	getFullState?: () => Promise<any>;
	setState?: (state: any) => Promise<void>;
	deployToSandbox?: () => Promise<any>;
	deployToAppEngine?: () => Promise<any>;
	getSummary?: () => Promise<any>;
	getPreviewUrlCache?: () => Promise<string>;
	pushToGitHub?: (options: any) => Promise<any>;
	// Sandbox-specific methods (when T is Sandbox)
	exec?: (command: string, options?: any) => Promise<any>;
	writeFile?: (path: string, content: string) => Promise<void>;
	readFile?: (path: string) => Promise<{ success: boolean; content?: string }>;
	// Additional methods that may be available on the stub
	[key: string]: any;
}

type DurableObjectID = string | { id: string; name: string };

// Durable Object Jurisdiction type
type DurableObjectJurisdiction = 'eu' | 'fedramp' | undefined;

// Cloudflare Workers ExecutionContext type
interface ExecutionContext {
	waitUntil(promise: Promise<any>): void;
	passThroughOnException(): void;
}

// Cloudflare Workers KVNamespace type
interface KVNamespace {
	get(key: string): Promise<string | null>;
	get(key: string, type: 'text'): Promise<string | null>;
	get(key: string, type: 'json'): Promise<any>;
	get(key: string, type: 'arrayBuffer'): Promise<ArrayBuffer | null>;
	get(key: string, type: 'stream'): Promise<ReadableStream | null>;
	put(key: string, value: string | ArrayBuffer | ArrayBufferView | ReadableStream): Promise<void>;
	put(key: string, value: string | ArrayBuffer | ArrayBufferView | ReadableStream, options?: { expirationTtl?: number; expiration?: number; metadata?: any }): Promise<void>;
	delete(key: string): Promise<void>;
	list(options?: { prefix?: string; limit?: number; cursor?: string }): Promise<{ keys: Array<{ name: string; expiration?: number; metadata?: any }>; list_complete: boolean; cursor?: string }>;
}

// Cloudflare Workers RateLimit type
interface RateLimit {
	limit(options: { key: string; limit?: number; period?: number }): Promise<{ success: boolean; limit?: number; remaining?: number; reset?: number }>;
}

// Cloudflare Workers WebSocketPair type
interface WebSocketPair {
	0: WebSocket;
	1: WebSocket;
}

// Cloudflare Workers DurableObject base class
declare class DurableObject {
	constructor(ctx: DurableObjectState, env: Env);
	fetch(request: Request): Promise<Response>;
}

// Cloudflare Workers DurableObjectState type
interface DurableObjectState {
	id: DurableObjectID;
	waitUntil(promise: Promise<any>): void;
	storage: DurableObjectStorage;
	getWebSockets(): WebSocket[];
}

// Cloudflare Workers DurableObjectStorage type
interface DurableObjectStorage {
	get<T = unknown>(key: string): Promise<T | undefined>;
	get<T = unknown>(keys: string[]): Promise<Map<string, T>>;
	put<T = unknown>(key: string, value: T): Promise<void>;
	put<T = unknown>(entries: Record<string, T>): Promise<void>;
	delete(key: string): Promise<boolean>;
	delete(keys: string[]): Promise<number>;
	list<T = unknown>(options?: { start?: string; end?: string; prefix?: string; reverse?: boolean; limit?: number }): Promise<Map<string, T>>;
	transaction<T>(closure: (txn: DurableObjectTransaction) => Promise<T>): Promise<T>;
	getAlarm(): Promise<number | null>;
	setAlarm(scheduledTime: number | Date): Promise<void>;
	deleteAlarm(): Promise<void>;
	sync(): Promise<void>;
}

// Cloudflare Workers DurableObjectTransaction type
interface DurableObjectTransaction {
	get<T = unknown>(key: string): Promise<T | undefined>;
	get<T = unknown>(keys: string[]): Promise<Map<string, T>>;
	put<T = unknown>(key: string, value: T): void;
	put<T = unknown>(entries: Record<string, T>): void;
	delete(key: string): void;
	delete(keys: string[]): void;
	rollback(): void;
}

// ResponseInit with webSocket support
interface ResponseInit {
	status?: number;
	statusText?: string;
	headers?: HeadersInit;
	webSocket?: WebSocket;
}

// AI Gateway Providers type (for Cloudflare Workers AI Gateway)
type AIGatewayProviders = 'cloudflare' | 'openai' | 'anthropic' | 'google' | 'cohere' | 'huggingface' | 'replicate' | 'custom';

declare namespace Cloudflare {
	interface Env {
		VibecoderStore: KVNamespace;
		TEMPLATES_REPOSITORY: "https://github.com/cloudflare/vibesdk-templates";
		ALLOWED_EMAIL: "";
		DISPATCH_NAMESPACE: "vibesdk-default-namespace";
		CLOUDFLARE_AI_GATEWAY: "vibesdk-gateway";
		ENABLE_READ_REPLICAS: "true";
		ANTHROPIC_API_KEY: string;
		OPENAI_API_KEY: string;
		GOOGLE_AI_STUDIO_API_KEY: string;
		OPENROUTER_API_KEY: string;
		CEREBRAS_API_KEY: string;
		GROQ_API_KEY: string;
		SANDBOX_SERVICE_API_KEY: string;
		SANDBOX_SERVICE_TYPE: string;
		SANDBOX_SERVICE_URL: string;
		CLOUDFLARE_API_TOKEN: string;
		CLOUDFLARE_ACCOUNT_ID: string;
		CLOUDFLARE_AI_GATEWAY_URL: string;
		CLOUDFLARE_AI_GATEWAY_TOKEN: string;
		SERPAPI_KEY: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		GITHUB_CLIENT_ID: string;
		GITHUB_CLIENT_SECRET: string;
		JWT_SECRET: string;
        AI_PROXY_JWT_SECRET: string;
		ENTROPY_KEY: string;
		ENVIRONMENT: string;
        USE_TUNNEL_FOR_PREVIEW: boolean;
		SECRETS_ENCRYPTION_KEY: string;
		MAX_SANDBOX_INSTANCES: string;
		SANDBOX_INSTANCE_TYPE: string;
		CUSTOM_DOMAIN: string;
		CUSTOM_PREVIEW_DOMAIN: string;
		ALLOCATION_STRATEGY: string;
		GITHUB_EXPORTER_CLIENT_ID: string;
		GITHUB_EXPORTER_CLIENT_SECRET: string;
		CF_ACCESS_ID: string;
		CF_ACCESS_SECRET: string;
		SENTRY_DSN: string;
		DEFAULT_DEPLOYMENT_TARGET?: 'cloudflare' | 'app_engine';
		GOOGLE_CLOUD_PROJECT_ID?: string;
		GOOGLE_SERVICE_ACCOUNT_KEY?: string;
		CodeGenObject: DurableObjectNamespace<import("./worker/index").CodeGeneratorAgent>;
		Sandbox: DurableObjectNamespace<import("./worker/index").UserAppSandboxService>;
		DORateLimitStore: DurableObjectNamespace<import("./worker/index").DORateLimitStore>;
		TEMPLATES_BUCKET: R2Bucket;
		DB: D1Database;
		DISPATCHER: DispatchNamespace;
		API_RATE_LIMITER: RateLimit;
		AUTH_RATE_LIMITER: RateLimit;
		AI: Ai;
		USE_CLOUDFLARE_IMAGES: boolean;
		CF_VERSION_METADATA: WorkerVersionMetadata;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TEMPLATES_REPOSITORY" | "ALLOWED_EMAIL" | "DISPATCH_NAMESPACE" | "CLOUDFLARE_AI_GATEWAY" | "ENABLE_READ_REPLICAS" | "ANTHROPIC_API_KEY" | "OPENAI_API_KEY" | "GOOGLE_AI_STUDIO_API_KEY" | "OPENROUTER_API_KEY" | "CEREBRAS_API_KEY" | "GROQ_API_KEY" | "SANDBOX_SERVICE_API_KEY" | "SANDBOX_SERVICE_TYPE" | "SANDBOX_SERVICE_URL" | "CLOUDFLARE_API_TOKEN" | "CLOUDFLARE_ACCOUNT_ID" | "CLOUDFLARE_AI_GATEWAY_URL" | "CLOUDFLARE_AI_GATEWAY_TOKEN" | "SERPAPI_KEY" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_CLIENT_ID" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "JWT_SECRET" | "ENTROPY_KEY" | "ENVIRONMENT" | "SECRETS_ENCRYPTION_KEY" | "MAX_SANDBOX_INSTANCES" | "SANDBOX_INSTANCE_TYPE" | "CUSTOM_DOMAIN" | "CUSTOM_PREVIEW_DOMAIN" | "ALLOCATION_STRATEGY" | "GITHUB_EXPORTER_CLIENT_ID" | "GITHUB_EXPORTER_CLIENT_SECRET" | "CF_ACCESS_ID" | "CF_ACCESS_SECRET" | "SENTRY_DSN">> {}
}
