-- Migration: 0005_agent_state_management
-- Description: Add agent sessions, phases, and template asset caching tables for Strategy B
-- Created: 2025-01-31 16:58
-- Strategy B: Pure Hono + PostgreSQL Implementation (Simplified)

-- ========================================
-- Agent Sessions (Durable Object equivalent)
-- ========================================

CREATE TABLE IF NOT EXISTS agent_sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    app_id TEXT REFERENCES apps(id) ON DELETE CASCADE,
    status VARCHAR(50) NOT NULL DEFAULT 'initialized'
        CHECK (status IN ('initialized', 'blueprint_generated', 'executing', 'reviewing', 'completed', 'failed')),

    -- Blueprint data (JSON structure defining the execution plan)
    blueprint JSONB,

    -- Phase tracking (array of phase objects with status)
    phases JSONB DEFAULT '[]',

    -- Runtime execution data (current state, variables, etc.)
    execution_data JSONB DEFAULT '{}',

    -- Metadata
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    aborted_at TIMESTAMP WITH TIME ZONE,

    -- Error tracking
    error_message TEXT,
    error_details JSONB,

    -- Resource usage tracking
    gcp_ai_tokens_used INTEGER DEFAULT 0,
    gcp_storage_operations INTEGER DEFAULT 0,
    execution_time_seconds INTEGER DEFAULT 0
);

-- Indexes for agent_sessions
CREATE INDEX IF NOT EXISTS idx_agent_sessions_user_id ON agent_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_app_id ON agent_sessions(app_id);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_status ON agent_sessions(status);
CREATE INDEX IF NOT EXISTS idx_agent_sessions_created_at ON agent_sessions(created_at);

-- ========================================
-- Agent Phases (Execution Steps)
-- ========================================

CREATE TABLE IF NOT EXISTS agent_phases (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES agent_sessions(id) ON DELETE CASCADE,

    -- Phase identification
    phase_name VARCHAR(100) NOT NULL,
    phase_type VARCHAR(50) NOT NULL
        CHECK (phase_type IN ('blueprint', 'analysis', 'code_generation', 'integration', 'review', 'deployment', 'completion')),
    phase_key VARCHAR(50), -- Unique key within session (e.g., 'blueprint', 'file_1', 'review_1')

    -- Status and priority
    status VARCHAR(50) NOT NULL DEFAULT 'pending'
        CHECK (status IN ('pending', 'running', 'completed', 'failed', 'skipped')),
    priority INTEGER DEFAULT 1,

    -- Configuration and input data
    config JSONB DEFAULT '{}',        -- Phase configuration parameters
    input_data JSONB,                        -- Data passed from previous phases

    -- Results and output
    result JSONB,                            -- Successful execution results
    output_files JSONB DEFAULT '[]',  -- Files generated by this phase

    -- Error handling
    error_message TEXT,
    error_details JSONB,
    retry_count INTEGER DEFAULT 0,

    -- Timing
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    queued_at TIMESTAMP WITH TIME ZONE,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,

    -- Dependencies (other phases this one depends on)
    depends_on JSONB DEFAULT '[]',    -- Array of phase IDs

    -- Resource usage for this phase
    phase_tokens_used INTEGER DEFAULT 0,
    phase_execution_time_seconds INTEGER DEFAULT 0
);

-- Indexes for agent_phases
CREATE INDEX IF NOT EXISTS idx_agent_phases_session_id ON agent_phases(session_id);
CREATE INDEX IF NOT EXISTS idx_agent_phases_type ON agent_phases(phase_type);
CREATE INDEX IF NOT EXISTS idx_agent_phases_status ON agent_phases(status);
CREATE INDEX IF NOT EXISTS idx_agent_phases_priority ON agent_phases(priority);
CREATE INDEX IF NOT EXISTS idx_agent_phases_created_at ON agent_phases(created_at);

-- ========================================
-- Template Assets Cache
-- ========================================

CREATE TABLE IF NOT EXISTS template_assets (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,

    -- Template identification
    template_name VARCHAR(100) NOT NULL,
    asset_path TEXT NOT NULL,

    -- Content and caching
    content_hash VARCHAR(64) NOT NULL,       -- SHA-256 hash of content
    cached_content TEXT,                     -- Actual file content (nullable for large files)
    is_large_file BOOLEAN DEFAULT false,     -- Flag for files that should be streamed

    -- Metadata
    file_size_bytes INTEGER,
    mime_type VARCHAR(100),
    last_accessed TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- GCS source information
    gcs_bucket TEXT,
    gcs_path TEXT,

    -- Usage statistics
    access_count INTEGER DEFAULT 0,
    last_used_in_session TEXT REFERENCES agent_sessions(id) ON DELETE SET NULL,

    UNIQUE(template_name, asset_path)
);

-- Indexes for template_assets
CREATE INDEX IF NOT EXISTS idx_template_assets_template_name ON template_assets(template_name);
CREATE INDEX IF NOT EXISTS idx_template_assets_content_hash ON template_assets(content_hash);
CREATE INDEX IF NOT EXISTS idx_template_assets_last_accessed ON template_assets(last_accessed);
CREATE INDEX IF NOT EXISTS idx_template_assets_access_count ON template_assets(access_count);

-- ========================================
-- Agent Logs and Audit Trail
-- ========================================

CREATE TABLE IF NOT EXISTS agent_execution_logs (
    id BIGSERIAL PRIMARY KEY,
    session_id TEXT REFERENCES agent_sessions(id) ON DELETE CASCADE,
    phase_id TEXT REFERENCES agent_phases(id) ON DELETE CASCADE,

    -- Log entry details
    level VARCHAR(20) NOT NULL DEFAULT 'info'
        CHECK (level IN ('debug', 'info', 'warn', 'error')),
    message TEXT NOT NULL,
    details JSONB DEFAULT '{}',

    -- Context
    component VARCHAR(100),                 -- Which component logged this (e.g., 'blueprint-generator', 'phase-executor')
    operation VARCHAR(100),                 -- What operation was being performed

    -- Timing and correlation
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    correlation_id TEXT,                    -- For tracking across distributed operations

    -- Performance data
    duration_ms INTEGER,                    -- How long this operation took
    memory_usage_mb INTEGER,                -- Memory usage at log time
    gcp_operations_count INTEGER DEFAULT 0  -- Number of GCP service calls
);

-- Indexes for agent_execution_logs
CREATE INDEX IF NOT EXISTS idx_execution_logs_session_id ON agent_execution_logs(session_id);
CREATE INDEX IF NOT EXISTS idx_execution_logs_phase_id ON agent_execution_logs(phase_id);
CREATE INDEX IF NOT EXISTS idx_execution_logs_level ON agent_execution_logs(level);
CREATE INDEX IF NOT EXISTS idx_execution_logs_timestamp ON agent_execution_logs(timestamp);
CREATE INDEX IF NOT EXISTS idx_execution_logs_component ON agent_execution_logs(component);

-- ========================================
-- WebSocket Connection Tracking
-- ========================================

CREATE TABLE IF NOT EXISTS websocket_connections (
    id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    session_id TEXT REFERENCES agent_sessions(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,

    -- Connection details
    connection_id TEXT UNIQUE NOT NULL,     -- Generated client-side ID
    client_ip TEXT,
    user_agent TEXT,
    protocol_version VARCHAR(10) DEFAULT '1.0',

    -- Connection state
    status VARCHAR(20) DEFAULT 'connected'
        CHECK (status IN ('connected', 'disconnected', 'error', 'closed')),
    connected_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    disconnected_at TIMESTAMP WITH TIME ZONE,
    last_ping TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,

    -- Performance tracking
    messages_sent INTEGER DEFAULT 0,
    messages_received INTEGER DEFAULT 0,
    bytes_sent INTEGER DEFAULT 0,
    bytes_received INTEGER DEFAULT 0,

    -- Error tracking
    error_count INTEGER DEFAULT 0,
    last_error TEXT,

    -- Cleanup
    expires_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP + INTERVAL '24 hours'
);

-- Indexes for websocket_connections
CREATE INDEX IF NOT EXISTS idx_websocket_connections_session_id ON websocket_connections(session_id);
CREATE INDEX IF NOT EXISTS idx_websocket_connections_user_id ON websocket_connections(user_id);
CREATE INDEX IF NOT EXISTS idx_websocket_connections_status ON websocket_connections(status);
CREATE INDEX IF NOT EXISTS idx_websocket_connections_expires_at ON websocket_connections(expires_at);

-- ========================================
-- Comments and Documentation
-- ========================================

COMMENT ON TABLE agent_sessions IS 'Agent execution sessions - equivalent to Cloudflare Durable Objects with PostgreSQL persistence';
COMMENT ON TABLE agent_phases IS 'Individual execution phases within an agent session';
COMMENT ON TABLE template_assets IS 'Cached template files for faster agent execution';
COMMENT ON TABLE agent_execution_logs IS 'Detailed execution logs for debugging and monitoring';
COMMENT ON TABLE websocket_connections IS 'Active WebSocket connections for real-time updates';

COMMENT ON COLUMN agent_sessions.phases IS 'JSON array tracking phase status and progress';
COMMENT ON COLUMN agent_sessions.execution_data IS 'Current execution state, variables, and context';
COMMENT ON COLUMN agent_phases.depends_on IS 'Array of phase IDs this phase depends on';
