// GCP-specific database schema for drizzle-kit
// This file is used by drizzle-kit for migrations and doesn't depend on runtime detection

import * as postgresSchema from './schema.gcp';

// Export the GCP schema directly for drizzle-kit
const {
	users,
	sessions,
	apiKeys,
	apps,
	favorites,
	stars,
	appLikes,
	commentLikes,
	appComments,
	appViews,
	oauthStates,
	authAttempts,
	passwordResetTokens,
	emailVerificationTokens,
	verificationOtps,
	auditLogs,
	userSecrets,
	userModelConfigs,
	userModelProviders,
	systemSettings,
	rateLimitBuckets,
	appDeployments,
} = postgresSchema;

export {
	users,
	sessions,
	apiKeys,
	apps,
	favorites,
	stars,
	appLikes,
	commentLikes,
	appComments,
	appViews,
	oauthStates,
	authAttempts,
	passwordResetTokens,
	emailVerificationTokens,
	verificationOtps,
	auditLogs,
	userSecrets,
	userModelConfigs,
	userModelProviders,
	systemSettings,
	rateLimitBuckets,
	appDeployments,
};

export type DatabaseSchema = typeof postgresSchema;

export type {
	User,
	NewUser,
	Session,
	NewSession,
	ApiKey,
	NewApiKey,
	App,
	NewApp,
	Favorite,
	NewFavorite,
	Star,
	NewStar,
	AppLike,
	NewAppLike,
	CommentLike,
	NewCommentLike,
	AppComment,
	NewAppComment,
	AppView,
	NewAppView,
	OAuthState,
	NewOAuthState,
	AuditLog,
	NewAuditLog,
	UserSecret,
	NewUserSecret,
	UserModelConfig,
	NewUserModelConfig,
	UserModelProvider,
	NewUserModelProvider,
	SystemSetting,
	NewSystemSetting,
	RateLimitBucketRecord,
	NewRateLimitBucketRecord,
	AppDeployment,
	NewAppDeployment,
	AppDeploymentTarget,
	AppDeploymentStatus,
} from './schema.sqlite';
